# Generated by Django 3.0.3 on 2020-05-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersocialauth',
            table='user_social_auth',
        ),
    ]
